---
# https://tekton.dev/docs/pipelines/install/
# https://github.com/shipwright-io/build/blob/main/docs/development/authentication.md
# https://github.com/shipwright-io/build/blob/main/samples/build/build_buildah_cr.yaml
# https://tekton.dev/docs/pipelines/taskruns/
# cat tektonbuild.yml | kubectl create -f -
apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: buildah-build-pulumi-runner
spec:
  source:
    url: https://{{ username }}:{{ token }}@github.com/usrbinkat/KongOnEKS.git
    contextDir: pulumi-runner
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  dockerfile: Dockerfile
  output:
    image: docker.io/katamo/pulumi
