name: pulumi-deploy
on:
  repository_dispatch:
    types: [pulumi-runner-deploy]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ github.actor }}/pulumi-runner:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      options: "--cpus 2"
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.client_payload.sha }}
    - name: Pulumi Runner Deploy
      run: |
        set -x;
        cd $(pwd)/pulumi;
        npm install;
        pulumi up --stack KongOnEKS --yes --non-interactive;
        pulumi stack --stack KongOnEKS output kubeconfig | tee /tmp/kubeconfig;
        aws s3 cp /tmp/kubeconfig s3://$(pulumi stack --stack KongOnEKS output adminBucketName);

