name: pulumi-deploy
on:
  repository_dispatch:
    types: [pulumi-runner-deploy]

# TODO convert pulumi shell scripts to pulumi/actions@v3 github actions plugin
# https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/#using-a-different-root-directory
jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ github.actor }}/pulumi-runner:latest
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PATH: /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      options: "--cpus 2"
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Test aws cli
      run: "aws sts get-caller-identity"

    - name: Install NPM Dependencies
      working-directory: pulumi
      run: "npm install"

    - name: Pulumi Up
      working-directory: pulumi
      run: "pulumi up --stack KongOnEKS --yes --non-interactive --suppress-outputs"

    - name: Pull .kube/config for subsequent tasks
      working-directory: pulumi
      run: "pulumi stack --stack KongOnEKS output kubeconfig > /root/.kube/config"

    - name: Test Kubeconfig | get nodes
      run: "KUBECONFIG=/root/.kube/config kubectl get nodes"

#   - name: Install + Configure Helm
#     run: |-
#       curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
#       helm repo add bitnami https://charts.bitnami.com/bitnami
