name: pulumi-deploy
on:
  repository_dispatch:
    types: [pulumi-runner-deploy]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ github.actor }}/${{ github.workflow }}:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      volumes:
        - ${{ github.action_path }}:/pulumi
      options: --cpus 1
