name: pulumi-deploy
on:
  repository_dispatch:
    types: [pulumi-runner-deploy]

# TODO convert pulumi shell scripts to pulumi/actions@v3 github actions plugin
# https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/#using-a-different-root-directory
jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ github.actor }}/pulumi-runner:latest
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PATH: /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      options: "--cpus 2"
    steps:

    - name: Git Checkout
      uses: actions/checkout@v3.0.1
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Test aws cli
      run: "aws sts get-caller-identity"

    - name: Install NPM Dependencies
      working-directory: pulumi
      run: "npm install"

    - name: Pulumi Up
      working-directory: pulumi
      run: |
        set -ex;
        pulumi stack select usrbinkat/Gateway/KongHybridGatewayOnEKS;
        pulumi config set aws:region us-east-1;
        pulumi config set eksCluster:clusterName KongOnEKS;
        pulumi config set --secret kong:dbPassword ${{ secrets.KONG_POSTGRES_PASSWD }};
        pulumi up --yes --non-interactive --suppress-outputs;
        aws s3 cp s3://$(pulumi stack output adminBucketName)/kubeconfig /root/.kube/config;

    - name: Test Kubeconfig | get nodes
      run: "KUBECONFIG=/root/.kube/config kubectl get nodes"