name: pulumi-deploy
on:
  repository_dispatch:
    types: [pulumi-runner-deploy]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ github.actor }}/pulumi-runner:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      options: "--cpus 2"
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.client_payload.sha }}
    - name: Pulumi Runner Deploy
      run: |
        set -x; cd $(pwd)/pulumi; npm install;
        pulumi up --stack KongOnEKS --yes --non-interactive --suppress-outputs;
    - name: Pulumi Runner Pull .kube/config for subsequent tasks
      run: "mkdir -p /root/.kube; cd $(pwd)/pulumi; pulumi stack --stack KongOnEKS output kubeconfig > /root/.kube/config"
    - name: Pulumi Runner test aws cli I
      run: "which aws"
    - name: Pulumi Runner test aws cli II
      run: "aws sts get-caller-identity"
#   - name: Pulumi Runner Test .kube/config
#     run: "KUBECONFIG=/root/.kube/config kubectl get nodes"
