name: pulumi-runner
on:
  repository_dispatch:
    types: [runner-image-build]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Login ghcr.io
      uses: docker/login-action@v1.14.1
      with:
        logout: true
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Git Checkout
      uses: actions/checkout@v3.0.1
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Build Image | ghcr.io/${{ github.actor }}/${{ github.workflow }}
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./${{ github.workflow }}
        file: ./${{ github.workflow }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/${{ github.workflow }}
          ghcr.io/${{ github.actor }}/${{ github.workflow }}:${{ github.sha }}
 
    - name: Trigger Pulumi Deploy
      if: success()
      uses: peter-evans/repository-dispatch@v2.0.0
      with:
        event-type: pulumi-runner-deploy
        token: ${{ secrets.GH_ACTIONS_TOKEN }}
        repository: ${{ github.repository }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
